### ISSUE TITLE
升级之后编译报错：Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by xxsser** [airyland/vux-loader#38]
vux-loader 版本： 1.1.19

之前一直正常，升级之后报错如下，有时间了希望看一下。

`Module build failed: TypeError: Cannot read property 'replace' of undefined
    at /xxx/node_modules/vux-loader/src/libs/get-less-variables.js:51:28
    at Array.forEach (<anonymous>)
    at getContent (/xxx/node_modules/vux-loader/src/libs/get-less-variables.js:21:28)
    at getLessVariables (/xxx/node_modules/vux-loader/src/libs/get-less-variables.js:6:10)
    at Object.module.exports (/xxx/node_modules/vux-loader/src/index.js:83:17)
`

**Comment by maliang** [comment]
我也报了同样的错，不知道哪里的问题

**Comment by airyland** [comment]
麻烦帖一下主题文件，我检查一下

**Comment by airyland** [comment]
抱歉，支持 import 其他文件引入的 bug，1.1.20 已修复。

**Comment by xxsser** [comment]
这效率，没得说
