### ISSUE TITLE
[Feature Request] 不支持webpack4

### ISSUE THREAD

**Issue by xecrom** [airyland/vux-loader#64]
### Existing Component
是

### Component Name
无 

### Description
webpack升级到4后不支持vux-loader，希望能支持webpack4

**Comment by ldwqh0** [comment]
个人感觉，作者应该放弃这个loader了，随着vue-loader15的发布，以前的很多痛点现在都能很好的解决了。感觉作者应该去掉vux里面对于vux-loader的依赖，专心的回到vux本身上面去。

**Comment by zzc5464** [comment]
我的天。。有解决办法了吗

**Comment by ldwqh0** [comment]
@zzc5464 问题的核心不在webpack4,而是vue-loader15,我们可以升级webpack而不升级 vue-loader
参见https://github.com/ldwqh0/vux-seed

**Comment by zzc5464** [comment]
非常感谢，降级vue-loader可行

**Comment by fengerzh** [comment]
亲测可行，把vue-loader降至14.0.0即可

**Comment by ExpGitHubUp** [comment]
> 非常感谢，降级vue-loader可行
降到多少?

@fengerzh 这位仁兄的14.0.0试了不行

`Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined`

更新成14.2.3
` error  in ./node_modules/vux/src/components/checklist/index.vue

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (d:\PhpProj\PHP\vux\vuxtest\node_modules\schema-utils\src\validateOptions.js:32:11)
    at Object.loader (d:\PhpProj\PHP\vux\vuxtest\node_modules\css-loader\dist\index.js:44:28)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js?{"minimize":false,"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!./node_modules/vux-loader/src/after-less-loader.js!./node_modules/less-loader/dist/cjs.js?{"sourceMap":false}!./node_modules/vux-loader/src/style-loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./node_modules/vux/src/components/checklist/index.vue 4:14-444 13:3-17:5 14:22-452
 @ ./node_modules/vux/src/components/checklist/index.vue`



**update:
修改style-loader 和css-loader顺序即可**

**Comment by dzjwan521** [comment]
> @zzc5464 问题的核心不在webpack4,而是vue-loader15,我们可以升级webpack而不升级 vue-loader
> 参见https://github.com/ldwqh0/vux-seed

好像用cssmodule的话  打包build有问题

**Comment by gottayan** [comment]
> 亲测可行，把vue-loader降至14.0.0即可

降级之后可以打包成功 但是按需模块打包有问题
index.js?366f:3 VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
